// @neowhale/storefront — Core entry point (no React)
export { WhaleClient } from './client.js'
export { PixelManager } from './pixels/pixel-manager.js'
export { resilientSend } from './resilient-send.js'
export type {
  Product,
  PricingTier,
  ProductVariation,
  Category,
  CategoryTreeNode,
  Cart,
  CartItem,
  TaxBreakdown,
  Order,
  OrderItem,
  Customer,
  Address,
  PaymentData,
  CustomerAnalytics,
  Location,
  SendCodeResponse,
  VerifyCodeResponse,
  StorefrontSession,
  ListResponse,
  WhaleStorefrontConfig,
  EventType,
  Review,
  ReviewSummary,
  WishlistItem,
  LoyaltyAccount,
  LoyaltyReward,
  LoyaltyTransaction,
  ShippingMethod,
  ShippingRate,
  CouponValidation,
  CheckoutSession,
  Recommendation,
  PixelConfig,
  StorefrontConfig,
  QRLandingData,
  QRLandingPage,
  QRLandingStore,
} from './types.js'
